[2024-08-05T13:14:45.468+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T13:14:45.516+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Los_Angeles scheduled__2024-08-05T09:00:00+00:00 [queued]>
[2024-08-05T13:14:45.526+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Los_Angeles scheduled__2024-08-05T09:00:00+00:00 [queued]>
[2024-08-05T13:14:45.526+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T13:14:45.548+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_air_pollution_data_Los_Angeles> on 2024-08-05 09:00:00+00:00
[2024-08-05T13:14:45.552+0300] {standard_task_runner.py:64} INFO - Started process 56646 to run task
[2024-08-05T13:14:45.557+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'air_pollution_data_dag', 'fetch_air_pollution_data_Los_Angeles', 'scheduled__2024-08-05T09:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/air_pollution_data_dag.py', '--cfg-path', '/tmp/tmpwv2o2bdg']
[2024-08-05T13:14:45.558+0300] {standard_task_runner.py:91} INFO - Job 251: Subtask fetch_air_pollution_data_Los_Angeles
[2024-08-05T13:14:45.634+0300] {task_command.py:426} INFO - Running <TaskInstance: air_pollution_data_dag.fetch_air_pollution_data_Los_Angeles scheduled__2024-08-05T09:00:00+00:00 [running]> on host std21092
[2024-08-05T13:14:45.743+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='air_pollution_data_dag' AIRFLOW_CTX_TASK_ID='fetch_air_pollution_data_Los_Angeles' AIRFLOW_CTX_EXECUTION_DATE='2024-08-05T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-05T09:00:00+00:00'
[2024-08-05T13:14:45.744+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T13:14:46.783+0300] {logging_mixin.py:188} INFO - Erreur lors de la récupération des données pour Los_Angeles
[2024-08-05T13:14:46.783+0300] {python.py:237} INFO - Done. Returned value was: None
[2024-08-05T13:14:46.784+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T13:14:46.791+0300] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=air_pollution_data_dag, task_id=fetch_air_pollution_data_Los_Angeles, run_id=scheduled__2024-08-05T09:00:00+00:00, execution_date=20240805T090000, start_date=20240805T101445, end_date=20240805T101446
[2024-08-05T13:14:46.860+0300] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-05T13:14:46.881+0300] {dagrun.py:940} ERROR - Failed to get task for ti <TaskInstance: air_pollution_data_dag.clean_data scheduled__2024-08-05T09:00:00+00:00 [None]>. Marking it as removed.
[2024-08-05T13:14:46.885+0300] {dagrun.py:940} ERROR - Failed to get task for ti <TaskInstance: air_pollution_data_dag.merge_data scheduled__2024-08-05T09:00:00+00:00 [None]>. Marking it as removed.
[2024-08-05T13:14:46.887+0300] {dagrun.py:940} ERROR - Failed to get task for ti <TaskInstance: air_pollution_data_dag.aggregate_data scheduled__2024-08-05T09:00:00+00:00 [None]>. Marking it as removed.
[2024-08-05T13:14:46.905+0300] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-05T13:14:46.924+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
